# Generated by Django 2.1.3 on 2018-11-26 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_option_name', models.CharField(max_length=255)),
                ('passenger_count', models.PositiveIntegerField()),
                ('air_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('air_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('air_taxes', models.DecimalField(decimal_places=2, max_digits=4)),
                ('air_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commit_deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('utilize_deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('estimate_id', models.AutoField(primary_key=True, serialize=False)),
                ('estimate_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('number_of_people', models.PositiveIntegerField()),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('R', 'Received'), ('C', 'Cancelled')], max_length=1)),
                ('destination', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_leg_name', models.CharField(max_length=255)),
                ('airline', models.CharField(max_length=255)),
                ('flight_num', models.PositiveIntegerField()),
                ('depart_from', models.CharField(max_length=255)),
                ('depart_air_code', models.CharField(max_length=3)),
                ('depart_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrive_into', models.CharField(max_length=255)),
                ('arrive_air_code', models.CharField(max_length=3)),
                ('arrive_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GroundOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_option_name', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('number_of_shuttles', models.PositiveIntegerField()),
                ('transfer_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_taxes', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pickup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('service_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupAir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_air_name', models.CharField(max_length=255)),
                ('air_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('group_air_options', models.ManyToManyField(to='estimates.AirOption')),
            ],
        ),
        migrations.CreateModel(
            name='GroupHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_hotel_name', models.CharField(max_length=255)),
                ('hotel_budget', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_transfer_name', models.CharField(max_length=255)),
                ('ground_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ground_options', models.ManyToManyField(to='estimates.GroundOption')),
            ],
        ),
        migrations.CreateModel(
            name='HotelOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_option_name', models.CharField(max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=255)),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_nights', models.PositiveIntegerField()),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('hotel_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_taxes', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='grouphotel',
            name='hotel_options',
            field=models.ManyToManyField(to='estimates.HotelOption'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='group_air',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimates.GroupAir'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='group_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimates.GroupHotel'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='group_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimates.GroupTransfer'),
        ),
        migrations.AddField(
            model_name='airoption',
            name='flight_legs',
            field=models.ManyToManyField(to='estimates.FlightLeg'),
        ),
    ]
