# Generated by Django 2.1.3 on 2018-11-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='title',
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Submitted'), ('C', 'Cancelled'), ('R', 'Received')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
