# Generated by Django 2.1.3 on 2018-11-21 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightleg',
            name='arrive_air_code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightleg',
            name='arrive_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
